### ISSUE TITLE
code plz?

### ISSUE THREAD

**Issue by zoeleesss** [CrowdDynamicsLab/GroupIM#1]
Could you provide the code of GroupIM, plz?
Thx!

**Comment by aravindsankar28** [comment]
Thanks for your interest in our work, the code will be released by the end of the month.

**Comment by Jhy1993** [comment]
> Thanks for your interest in our work, the code will be released by the end of the month.

Tomorrow is the end of this month😃

**Comment by aravindsankar28** [comment]
Thanks for the reminder, the code is up now!
