### ISSUE TITLE
Question about the dataset construction

### ISSUE THREAD

**Issue by FizzerYu** [CrowdDynamicsLab/GroupIM#3]
Hi
I am a new learner of Group Recommendation, and I just download the Yelp dataset. It's hard for me to construction the dataset following your paper. Could you please provide the details of dataset construction (Yelp).
Thank you very much!

**Comment by LIWEIDENG0830** [comment]
> 

Hi, FizzerYu.
I recently work on the group recommendation problem and want to run some SoTA models firstly. But I found that lots of processed datasets are not released. Do you have the idea about how to process these datasets, such as Yelp and Gowalla?
I would really appreciate it if you can help me!
