### ISSUE TITLE
How can you obtain the topK score? 

### ISSUE THREAD

**Issue by qywang-github** [CrowdDynamicsLab/GroupIM#4]
I cannot understand the process of getting topK scores.
I assume that the topK score can be obtained by multiplying the group and item embbeding.  However, I cannot find the item embedding.
How can you obtain the topK score? 
Thank you for your repy.

**Comment by aravindsankar28** [comment]
Check https://github.com/CrowdDynamicsLab/GroupIM/blob/master/models/models.py#L59 -- the group_predictor is a linear layer which parameterizes the item embeddings.
